/**
 * Doctor Talos's Traveling Show — Blog Engine
 *
 * Loads posts from posts/ directory as JSON.
 * Handles both the blog index (blog.html) and individual post view (post.html).
 */
(function () {
  // Post manifest — auto-generated by publish.sh
  var POST_SLUGS = [];

  var isPostPage = window.location.pathname.indexOf('post.html') !== -1;

  // Resolve base path for fetch URLs (handles pretty URLs / subdir serving)
  var basePath = window.location.pathname.substring(0, window.location.pathname.lastIndexOf('/') + 1);

  // Load manifest then render
  var xhr = new XMLHttpRequest();
  xhr.open('GET', basePath + 'posts/index.json', true);
  xhr.onload = function () {
    if (xhr.status === 200) {
      try { POST_SLUGS = JSON.parse(xhr.responseText); } catch (e) {}
    }
    if (isPostPage) {
      loadSinglePost();
    } else {
      loadPostIndex();
    }
  };
  xhr.onerror = function () {
    if (isPostPage) loadSinglePost();
    else loadPostIndex();
  };
  xhr.send();

  function loadPostIndex() {
    var container = document.getElementById('posts-container');
    if (!container) return;

    container.innerHTML = '';

    var loaded = 0;
    var posts = [];

    POST_SLUGS.forEach(function (slug, index) {
      fetchPost(slug, function (post) {
        posts[index] = post;
        loaded++;
        if (loaded === POST_SLUGS.length) {
          renderPostIndex(container, posts.filter(Boolean));
        }
      });
    });
  }

  function renderPostIndex(container, posts) {
    if (posts.length === 0) {
      container.innerHTML = '<p style="text-align:center; color: var(--gold-dim); font-style: italic;">No dispatches have been posted yet. The Doctor is composing.</p>';
      return;
    }

    posts.forEach(function (post) {
      var card = document.createElement('div');
      card.className = 'post-card fade-in';
      card.onclick = function () {
        window.location.href = 'post.html?slug=' + post.slug;
      };

      var preview = post.content[0] || '';
      if (preview.length > 200) {
        preview = preview.substring(0, 200) + '...';
      }

      card.innerHTML =
        '<div class="post-date">' + escapeHtml(post.dateDisplay) + '</div>' +
        '<div class="post-title">' + escapeHtml(post.title) + '</div>' +
        (post.subtitle ? '<div style="font-style: italic; color: var(--burgundy-deep); font-size: 0.9rem; margin-bottom: 0.5rem;">' + escapeHtml(post.subtitle) + '</div>' : '') +
        '<div class="post-preview">' + escapeHtml(preview) + '</div>' +
        '<span class="read-more">Read this dispatch →</span>';

      container.appendChild(card);
    });
  }

  function loadSinglePost() {
    var params = new URLSearchParams(window.location.search);
    var slug = params.get('slug');

    if (!slug) {
      showPostError('No dispatch specified. Perhaps you took a wrong turn.');
      return;
    }

    fetchPost(slug, function (post) {
      if (!post) {
        showPostError('This dispatch could not be found. It may have been consumed by entropy.');
        return;
      }

      document.title = post.title + ' — Doctor Talos\'s Traveling Show';

      var header = document.getElementById('post-header');
      header.innerHTML =
        '<h1>' + escapeHtml(post.title) + '</h1>' +
        (post.subtitle ? '<p class="subtitle">' + escapeHtml(post.subtitle) + '</p>' : '') +
        '<div class="post-meta"><span class="date">' + escapeHtml(post.dateDisplay) + '</span></div>';

      var body = document.getElementById('post-body');
      body.innerHTML = '';
      post.content.forEach(function (para, i) {
        var p = document.createElement('p');
        if (i === 0) p.className = 'drop-cap';
        p.innerHTML = para; // Allow HTML in post content
        body.appendChild(p);
      });

      // Post navigation
      var currentIndex = POST_SLUGS.indexOf(slug);
      if (currentIndex !== -1) {
        var nav = document.getElementById('post-nav');
        nav.style.display = '';

        var prevLink = document.getElementById('prev-link');
        var nextLink = document.getElementById('next-link');

        if (currentIndex < POST_SLUGS.length - 1) {
          prevLink.innerHTML = '<a href="post.html?slug=' + POST_SLUGS[currentIndex + 1] + '">← Previous Dispatch</a>';
        }
        if (currentIndex > 0) {
          nextLink.innerHTML = '<a href="post.html?slug=' + POST_SLUGS[currentIndex - 1] + '">Next Dispatch →</a>';
        }
      }
    });
  }

  function fetchPost(slug, callback) {
    var xhr = new XMLHttpRequest();
    xhr.open('GET', basePath + 'posts/' + slug + '.json', true);
    xhr.onload = function () {
      if (xhr.status === 200) {
        try {
          callback(JSON.parse(xhr.responseText));
        } catch (e) {
          callback(null);
        }
      } else {
        callback(null);
      }
    };
    xhr.onerror = function () {
      callback(null);
    };
    xhr.send();
  }

  function showPostError(message) {
    var header = document.getElementById('post-header');
    header.innerHTML = '<h2 style="color: var(--burgundy);">Dispatch Not Found</h2>' +
      '<p class="subtitle">' + escapeHtml(message) + '</p>';
  }

  function escapeHtml(str) {
    var div = document.createElement('div');
    div.appendChild(document.createTextNode(str));
    return div.innerHTML;
  }
})();
